require({
    packages: [
        {
            name: 'agrc',
            location: 'Content/viewer/agrc'
        }, {
            name: 'app',
            location: 'Content/viewer/app'
        }, {
            name: 'dgrid',
            location: 'Content/viewer/dgrid'
        }, {
            name: 'dgrid1',
            location: 'Content/viewer/dgrid1'
        }, {
            name: 'dgauges',
            location: 'Content/viewer/dgauges'
        }, {
            name: 'dijit',
            location: 'Content/viewer/dijit'
        }, {
            name: 'dojo',
            location: 'Content/viewer/dojo'
        }, {
            name: 'dojox',
            location: 'Content/viewer/dojox'
        }, {
            name: 'dstore',
            location: 'Content/viewer/dstore'
        }, {
            name: 'esri',
            location: 'Content/viewer/esri'
        }, {
            name: 'ijit',
            location: 'Content/viewer/ijit'
        }, {
            name: 'layer-selector',
            location: 'Content/viewer/layer-selector'
        }, {
            name: 'moment',
            location: 'Content/viewer/moment'
        }, {
            name: 'put-selector',
            location: 'Content/viewer/put-selector'
        }, {
            name: 'xstyle',
            location: 'Content/viewer/xstyle'
        }, {
            name: 'bootstrap',
            location: './bootstrap',
            main: 'Content/viewer/dist/js/bootstrap'
        }, {
            name: 'jquery',
            location: 'Content/viewer/jquery/dist',
            main: 'jquery'
        }, {
            name: 'ladda',
            location: 'Content/viewer/ladda-bootstrap',
            main: 'dist/ladda'
        }, {
            name: 'mustache',
            location: 'Content/viewer/mustache',
            main: 'mustache'
        }, {
            name: 'spin',
            location: 'Content/viewer/spinjs',
            main: 'spin'
        }
    ]
});
